import { useState } from 'react';
import { ArrowRight, Backpack, Car, ChatsCircle, GraduationCap, LockKey, Shield, Star, Wrench } from '@phosphor-icons/react';
import { contacts, items, skillKeys } from '../data';
import { rankFor, skillLabels, trainingCost } from '../game/engine';
import type { ScreenProps } from './view-types';
import { Bar, Button, money, Pagination, Tabs, Tag, usePagination } from './components';

export function Character({state,act,open}:ScreenProps){
  const [tab,setTab]=useState('skills');const [filter,setFilter]=useState('all');
  const itemList=items.filter(i=>filter==='all'||(filter==='owned'?state.inventory.includes(i.id):i.category===filter));
  const page=usePagination(itemList,8,4,filter);const contactPage=usePagination(contacts,6,3);const skillsPage=usePagination(skillKeys,6,4);
  const itemIcons={tools:Wrench,equipment:Shield,vehicles:Car,special:Star};
  return <><div className="page-heading"><div><span className="eyebrow">BECOME THE NAME THEY REMEMBER.</span><h1>Your character.</h1></div><GraduationCap size={30} className="heading-icon"/></div><div className="character-banner"><img src={state.player.portrait} alt="Your fully masked character"/><div><Tag tone="gold">{rankFor(state.stats.reputation)}</Tag><h2>{state.player.name}</h2><span>{state.stats.reputation} reputation · Day {state.day}</span></div><div className="character-record"><strong>{state.counters.jobsSucceeded}</strong><span>successful operations</span></div></div><Tabs options={[{id:'skills',label:'Skills'},{id:'inventory',label:'Inventory',count:state.inventory.length},{id:'contacts',label:'Contacts'}]} value={tab} onChange={setTab}/>
  {tab==='skills'&&<><div className="skill-grid">{skillsPage.visible.map(s=><article className="skill-card" key={s}><div className="skill-card-heading"><h3>{skillLabels[s]}</h3><strong>{state.skills[s]}<small>/10</small></strong></div><div className="skill-pips">{Array.from({length:10},(_,i)=><span className={i<state.skills[s]?'filled':''} key={i}/>)}</div><div className="skill-footer"><span>{state.skillXp[s]} XP</span><button className="mini-button" disabled={state.skills[s]>=10||state.stats.energy<20||state.stats.cash<trainingCost(state,s)||Boolean(state.jail)} onClick={()=>act({type:'TRAIN',skill:s})}>{state.skills[s]>=10?'Mastered':`Train · ${money(trainingCost(state,s))}`}<ArrowRight size={14}/></button></div></article>)}</div>{skillsPage.pages>1&&<Pagination {...skillsPage}/>}<p className="section-note">Operations build skill XP. Training costs 20 energy and advances one level.</p></>}
  {tab==='inventory'&&<><div className="filter-chips">{['all','owned','tools','equipment','vehicles','special'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='all'?'All items':f.charAt(0).toUpperCase()+f.slice(1)}</button>)}</div><div className="item-grid">{page.visible.map(item=>{const owned=state.inventory.includes(item.id);const Icon=itemIcons[item.category];return <button className="item-card" key={item.id} onClick={()=>open({kind:'item',id:item.id})}><div className="item-image"><img src={item.image} alt={item.name}/>{owned&&<Tag tone="gold">OWNED</Tag>}</div><div className="item-body"><span><Icon size={12}/>{item.category}</span><h3>{item.name}</h3><strong>{owned?'View item':money(item.cost)}</strong>{state.stats.reputation<item.requiredRep&&<LockKey size={13}/>}</div></button>;})}</div>{itemList.length===0&&<div className="empty-state"><Backpack size={30}/><h3>Travel light. Plan ahead.</h3><p>Tools and equipment improve your chances on every operation.</p><Button variant="secondary" onClick={()=>setFilter('all')}>Browse equipment</Button></div>}<Pagination {...page}/></>}
  {tab==='contacts'&&<><div className="contact-grid">{contactPage.visible.map(c=>{const unlocked=state.stats.reputation>=c.requiredRep;const relationship=state.relationships[c.id]??c.initialRelationship;return <button className={`contact-card ${!unlocked?'locked':''}`} key={c.id} onClick={()=>open({kind:'contact',id:c.id})}><img src={c.portrait} alt="Fully masked contact"/><div><span className="eyebrow">{c.role}</span><h3>{c.name}</h3><div className="contact-trust"><Bar value={relationship} label={`${c.name} relationship`}/><span>{unlocked?`${relationship}% trust`:`${c.requiredRep} REP`}</span></div></div>{unlocked?<ChatsCircle size={22}/>:<LockKey size={20}/>}</button>;})}</div><Pagination {...contactPage}/></>}
  </>;
}
