import { useState } from 'react';
import { ArrowRight, Heart, LockKey, UsersThree } from '@phosphor-icons/react';
import { crew } from '../data';
import { crewSalary } from '../game/engine';
import { getStrategy } from '../game/strategy';
import type { ScreenProps } from './view-types';
import { Bar, Button, money, Pagination, Tabs, Tag, usePagination } from './components';

export function Crew({state,act,open}:ScreenProps){
  const strategy=getStrategy(state);
  const [tab,setTab]=useState(state.crew.length?'owned':'recruit');
  const list=crew.filter(c=>tab==='owned'?state.crew.includes(c.id):!state.crew.includes(c.id));
  const pagination=usePagination(list,4,2,tab);
  return <><div className="page-heading"><div><span className="eyebrow">TRUST IS THE REAL CURRENCY.</span><h1>Your inner circle.</h1><p>The right people change everything.</p></div><UsersThree size={30} className="heading-icon"/></div><div className="crew-summary"><span><UsersThree size={17}/><strong>{state.crew.length}</strong> on your payroll</span><span>Daily salaries <strong>{money(crewSalary(state))}</strong></span></div><Tabs options={[{id:'owned',label:'Your crew',count:state.crew.length},{id:'recruit',label:'Recruitment',count:crew.length-state.crew.length}]} value={tab} onChange={setTab}/><div className="crew-grid">{pagination.visible.map(c=>{const owned=state.crew.includes(c.id);const unlocked=state.stats.reputation>=c.requiredRep;const loyalty=state.crewLoyalty[c.id]??c.loyalty;return <article className="crew-card" key={c.id}><button className="crew-card-art" onClick={()=>open({kind:'crew',id:c.id})}><img src={c.portrait} alt={`${c.alias}, fully masked ${c.role.toLowerCase()}`}/><Tag tone="glass">{c.role}</Tag></button><div className="crew-card-body"><div className="crew-name"><div><span className="eyebrow">{c.name}</span><h3>{c.alias}</h3></div><span className="crew-rating">{c.rating}<small>/10</small></span></div><p className="crew-trait">{c.trait}</p><div className="loyalty-row"><span>{state.crewInjured[c.id]>0?<><Heart size={13}/>{state.crewInjured[c.id]} days injured</>:'Loyalty'}</span><strong>{loyalty}%</strong></div><Bar value={loyalty} label={`${c.alias} loyalty`}/>{owned&&<div className="crew-fatigue-line"><span>{strategy.crewFatigue[c.id]??0}% fatigue</span><span>·</span><span>{Object.values(strategy.zones).some(z=>z.lieutenantId===c.id)?"Zone lieutenant":"Field crew"}</span></div>}<div className="crew-cost"><span>{money(c.salary)} / day</span>{!owned&&<strong>{money(c.cost)} signing fee</strong>}</div>{owned?<Button variant="secondary" onClick={()=>open({kind:'crew',id:c.id})}>View profile<ArrowRight size={15}/></Button>:<Button variant="secondary" disabled={!unlocked||state.stats.cash<c.cost||Boolean(state.jail)} onClick={()=>act({type:'RECRUIT',id:c.id})}>{!unlocked?`${c.requiredRep} REP required`:state.stats.cash<c.cost?'More cash needed':'Recruit'}{unlocked?<ArrowRight size={15}/>:<LockKey size={15}/>}</Button>}</div></article>;})}</div>{list.length===0&&<div className="empty-state"><UsersThree size={32}/><h3>No one rises alone.</h3><p>Find a specialist. Keep them paid. Earn their loyalty.</p><Button onClick={()=>setTab('recruit')}>Find your first recruit<ArrowRight size={16}/></Button></div>}<Pagination {...pagination}/></>;
}
