import { useState } from 'react';
import { ArrowRight, Bank, Buildings, Crown, House, LockKey, ShieldCheck, TrendUp, Wrench } from '@phosphor-icons/react';
import { businesses, districts, safehouseUpgrades } from '../data';
import { businessUpgradeCost, crewSalary, dailyIncome, safehouseUpgradeCost } from '../game/engine';
import type { ScreenProps } from './view-types';
import { Bar, Button, money, Pagination, Tabs, Tag, usePagination } from './components';

export function Empire({state,act,open}:ScreenProps) {
  const [tab,setTab]=useState('businesses');const [filter,setFilter]=useState('all');
  const list=businesses.filter(b=>filter==='all'||(filter==='owned'?state.businesses.some(o=>o.id===b.id):b.type===filter));
  const pagination=usePagination(list,4,1,filter);const territories=usePagination(districts,6,2);const upgrades=usePagination(safehouseUpgrades,4,2);
  const safehouseIcons=[House,ShieldCheck,Wrench,Buildings];
  return <><div className="page-heading"><div><span className="eyebrow">BUILD SOMETHING THAT LASTS.</span><h1>Your empire.</h1><p>Let your money do the work.</p></div><Crown size={30} className="heading-icon"/></div><div className="empire-ledger"><div><span>Daily income</span><strong>{money(dailyIncome(state))}</strong></div><div><span>Crew payroll</span><strong>−{money(crewSalary(state))}</strong></div><div><span>Net per day</span><strong className="gold-text">{money(dailyIncome(state)-crewSalary(state))}</strong></div></div><Tabs options={[{id:'businesses',label:'Businesses',count:state.businesses.length},{id:'safehouse',label:'Safehouse'},{id:'territory',label:'Territory'}]} value={tab} onChange={setTab}/>
  {tab==='businesses'&&<><div className="filter-chips">{[{id:'all',label:'All ventures'},{id:'owned',label:'Owned'},{id:'legitimate',label:'Legitimate'},{id:'illegal',label:'Underground'}].map(c=><button key={c.id} className={filter===c.id?'active':''} onClick={()=>setFilter(c.id)}>{c.label}</button>)}</div><div className="business-grid">{pagination.visible.map(b=>{const owned=state.businesses.find(o=>o.id===b.id);const unlocked=state.stats.reputation>=b.requiredRep;const upgrade=businessUpgradeCost(state,b.id);const income=dailyIncome({...state,businesses:[{id:b.id,level:owned?.level??1}]});return <article className="business-card" key={b.id}><div className="business-art" style={{backgroundImage:`url(${b.image})`}}><Tag tone="glass">{b.type==='legitimate'?'LEGITIMATE':'UNDERGROUND'}</Tag>{owned&&<Tag tone="gold">LEVEL {owned.level}</Tag>}</div><div className="business-body"><div className="business-title"><h3>{b.name}</h3><Bank size={20}/></div><p>{b.description}</p><p className="business-risk">{b.heat>0?'+':''}{b.heat*(owned?.level??1)} Heat / day · {b.type==='illegal'?'Raid risk rises with Heat':'Legitimate venture'}</p><div className="business-numbers"><div><span>Income / day</span><strong>+{money(income)}</strong></div><div><span>{owned?'Upgrade':'Buy-in'}</span><strong>{money(owned?upgrade:b.cost)}</strong></div></div>{owned?<Button variant="secondary" disabled={owned.level>=b.maxLevel||state.stats.cash<upgrade||Boolean(state.jail)} onClick={()=>act({type:'UPGRADE_BUSINESS',id:b.id})}>{owned.level>=b.maxLevel?'Fully upgraded':'Upgrade business'}<TrendUp size={15}/></Button>:<Button variant="secondary" disabled={!unlocked||state.stats.cash<b.cost||Boolean(state.jail)} onClick={()=>act({type:'BUY_BUSINESS',id:b.id})}>{!unlocked?`${b.requiredRep} reputation required`:state.stats.cash<b.cost?'More cash needed':'Acquire business'}{unlocked?<ArrowRight size={15}/>:<LockKey size={15}/>}</Button>}</div></article>;})}</div>{list.length===0&&<div className="empty-state"><Bank size={30}/><h3>Your first investment awaits.</h3><p>Acquire a business to collect income when you end the day.</p><Button variant="secondary" onClick={()=>setFilter('all')}>Find a venture<ArrowRight size={16}/></Button></div>}<Pagination {...pagination}/></>}
  {tab==='safehouse'&&<><div className="safehouse-banner" style={{backgroundImage:'linear-gradient(90deg,rgba(15,16,17,.94),rgba(15,16,17,.4)),url(/assets/business-6.webp)'}}><Tag tone="gold">YOUR BASE OF OPERATIONS</Tag><h2>A place to disappear.</h2><span>{Object.values(state.safehouse).reduce((sum,n)=>sum+n,0)} upgrades installed</span></div><div className="upgrade-grid">{upgrades.visible.map(u=>{const Icon=safehouseIcons[safehouseUpgrades.findIndex(entry=>entry.id===u.id)%4];const level=state.safehouse[u.id]??0;const price=safehouseUpgradeCost(state,u.id);return <article className="upgrade-card" key={u.id}><div className="upgrade-top"><div className="upgrade-icon"><Icon size={25}/></div><Tag>LVL {level}/{u.maxLevel}</Tag></div><h3>{u.name}</h3><p>{u.description}</p><span className="upgrade-bonus">{u.bonus}</span><Button variant="secondary" disabled={level>=u.maxLevel||state.stats.cash<price||Boolean(state.jail)} onClick={()=>act({type:'UPGRADE_SAFEHOUSE',id:u.id})}>{level>=u.maxLevel?'Fully upgraded':`Upgrade · ${money(price)}`}<ArrowRight size={15}/></Button></article>;})}</div><Pagination {...upgrades}/></>}
  {tab==='territory'&&<><div className="section-note">Influence pays in safer operations and stronger daily returns.</div><div className="territory-list">{territories.visible.map(d=>{const value=state.territories[d.id]??0;const unlocked=state.stats.reputation>=d.requiredRep;return <article className="territory-card" key={d.id}><img src={d.image} alt={d.name}/><div className="territory-copy"><div><h3>{d.name}</h3><Tag tone={value>=70?'gold':''}>{value>=70?'CONTROLLED':`${value}% influence`}</Tag></div><p>{d.gang}</p><Bar value={value} label={`${d.name} territory`}/><div className="territory-actions"><Button variant="secondary" disabled={!unlocked||Boolean(state.jail)||(state.districtId!==d.id&&state.stats.energy<5)||value>=100} onClick={()=>state.districtId===d.id?open({kind:'territory',id:d.id}):act({type:'TRAVEL',id:d.id})}>{!unlocked?`${d.requiredRep} REP required`:value>=100?'District controlled':state.districtId===d.id?'Build influence':'Travel here · 5 energy'}<ArrowRight size={15}/></Button></div></div></article>;})}</div><Pagination {...territories}/></>}
  </>;
}
