import { useState } from 'react';
import { ArrowRight, Flag, Lightning, Shield, Target, UsersThree } from '@phosphor-icons/react';
import { Button, Modal, Tabs } from './components';

const chapters = [
  { id: 'basics', label: 'Basics', icon: Lightning, title: 'Make each day count.', steps: ['Read cash, energy and odds before committing. Preparation improves the chance but has a real cost.', 'Choose an answer when an event appears. You can leave many opportunities without spending resources.', 'End the day to refill energy, heal, rest your crew and settle income, salaries and zone upkeep.', 'Heat above 65 can lead to arrest. Lay low, use quieter priorities or build useful contacts.'] },
  { id: 'zones', label: 'Zones', icon: Flag, title: 'A connected empire holds.', steps: ['Tap a numbered zone on the map. Its card shows your control, rival and route status.', 'Scout for intel. Negotiate to gain control, or commit crew to a three-round dispute.', 'Keep captured zones linked to Market Street through neighboring owned zones. Isolated ground earns less.', 'Fortify and assign a loyal lieutenant. Rivals test weak ground at the end of each day; truces buy time.'] },
  { id: 'crew', label: 'Crew', icon: UsersThree, title: 'People are the investment.', steps: ['Specialties, loyalty, fatigue and equipment all change your odds.', 'A crew member assigned as a lieutenant cannot join attacks or major operations.', 'Attack choices trade momentum for exposure. Cover protects the team, but safe choices alone rarely win ground.', 'Withdraw before morale or health collapses. End the day to rest; use the infirmary to recover injuries faster.'] },
  { id: 'ops', label: 'Major ops', icon: Target, title: 'Plan beyond the first move.', steps: ['Check reputation, crew and equipment in the plan before paying the entry cost.', 'Each stage changes progress and suspicion. A setback can be recovered from; repeated exposure can end the attempt.', 'Choices disclose their own cash, energy and chance. Patient paths let you continue when cash is tight.', 'You can withdraw. Entry costs stay spent; successful repeatable operations reopen after their cooldown.'] },
];
export function FieldGuide({ onClose }: { onClose: () => void }) {
  const [tab, setTab] = useState('basics'), chapter = chapters.find(c => c.id === tab)!;
  return <Modal title="Field guide" onClose={onClose} className="strategy-modal field-guide"><div className="strategy-dialog-heading"><span className="eyebrow">BLACKWATER FIELD GUIDE</span><h2>Know your next move.</h2></div><Tabs options={chapters.map(c => ({ id: c.id, label: c.label }))} value={tab} onChange={setTab} /><div className="guide-chapter"><chapter.icon size={30} /><h3>{chapter.title}</h3><ol>{chapter.steps.map(step => <li key={step}>{step}</li>)}</ol></div><div className="guide-principle"><Shield size={20} /><span>The previews already include your skills, crew, priority and challenge setting.</span></div><Button className="full-width" variant="secondary" onClick={onClose}>Back to the city<ArrowRight size={17} /></Button></Modal>;
}
