import { useState } from 'react';
import { ArrowRight, Bank, CheckCircle, Diamond, Fire, Heart, Lightning, LockKey, MoonStars, Star, Target, UsersThree, WarningCircle } from '@phosphor-icons/react';
import { activities, contacts, crew, districts, events, heist, items } from '../data';
import { bailCost, contactCost, contactEffects, crewSalary, dailyIncome, eventChance, eventChoiceRequirements, heatGain, heistChance, heistRequirements, influenceChance, influenceCost, jobChance, jobFailureEffects, layLowCost, skillLabels } from '../game/engine';
import type { Effects, StatKey } from '../game/types';
import type { Overlay, ScreenProps } from './view-types';
import { Bar, Button, Modal, money, Pagination, Requirement, Tag, usePagination } from './components';

const effectLabels:Record<StatKey,string>={cash:'Cash',reputation:'REP',heat:'Heat',health:'Health',energy:'Energy',influence:'Influence'};
const effectIcons={cash:Bank,reputation:Star,heat:Fire,health:Heart,energy:Lightning,influence:Target};
const signed=(value:number,cash=false)=>`${value>0?'+':'−'}${cash?money(Math.abs(value)):Math.abs(value)}`;
const relationshipName=(id:string)=>contacts.find(c=>c.id===id)?.name.split(' ')[0]??id;
export function EffectChips({effects,large=false}:{effects:Effects;large?:boolean}) {
  return <div className={`effect-chips ${large?'large':''}`}>{(Object.keys(effectLabels)as StatKey[]).filter(k=>effects[k]).map(k=>{const value=effects[k]!;const beneficial=k==='heat'?value<0:value>0;const Icon=effectIcons[k];return <span className={beneficial?'benefit':'loss'} key={k}><Icon size={14}/><strong>{value>0?'+':'−'}{k==='cash'?money(Math.abs(value)):Math.abs(value)}</strong><small>{k==='cash'?'':effectLabels[k]}</small></span>;})}{effects.loyalty&&<span><UsersThree size={14}/>{effects.loyalty>0?'+':''}{effects.loyalty} loyalty</span>}{effects.jailDays&&<span className="loss"><LockKey size={14}/>{effects.jailDays>0?'+':''}{effects.jailDays} jail days</span>}{effects.injuredCrew&&<span className="loss"><UsersThree size={14}/>Crew injury</span>}{effects.influenceDistrict&&<span className={effects.influenceDistrict>0?'benefit':'loss'}>{signed(effects.influenceDistrict)}% territory</span>}{Object.entries(effects.relationships??{}).filter(([,value])=>value!==0).map(([id,value])=><span className={value>0?'benefit':'loss'} key={id}>{signed(value)} {relationshipName(id)} trust</span>)}{effects.item&&<span className="benefit">{items.find(i=>i.id===effects.item)?.name??'New item'}</span>}</div>;
}
function failureSummary(effects:Effects){
  const pieces=Object.entries(effects).filter(([key,value])=>key in effectLabels&&typeof value==='number'&&value!==0).map(([key,value])=>`${signed(Number(value),key==='cash')} ${effectLabels[key as StatKey]}`);
  if(effects.loyalty)pieces.push(`${signed(effects.loyalty)} crew loyalty`);
  if(effects.jailDays)pieces.push(`${signed(effects.jailDays)} jail ${Math.abs(effects.jailDays)===1?'day':'days'}`);
  if(effects.influenceDistrict)pieces.push(`${signed(effects.influenceDistrict)}% territory`);
  if(effects.injuredCrew)pieces.push('Crew injury · 2 days');
  for(const [id,value] of Object.entries(effects.relationships??{}))if(value)pieces.push(`${signed(value)} ${relationshipName(id)} trust`);
  return pieces.join(' · ');
}

export function JobDialog({state,act}:ScreenProps){
  const job=activities.find(a=>a.id===state.pendingJob?.activityId);if(!job)return null;
  const scout=state.crew.some(id=>(state.crewInjured[id]??0)===0&&(state.crewLoyalty[id]??0)>=35);
  const failure=jobFailureEffects(state,job);
  const extraLoss={...failure,cash:job.failure.cash??0,energy:job.failure.energy??0};
  const approaches=[
    {id:'rush' as const,label:job.id==='old-warehouse'?'Raid immediately':'Act immediately',text:'Act now. Keep preparation lean.',cost:job.cost,energy:job.energy},
    {id:'informant' as const,label:'Pay an informant',text:'Buy confidence before committing.',cost:job.cost+Math.max(250,Math.round(job.cost*.6)),energy:job.energy},
    {id:'scout' as const,label:'Send a crew member to scout',text:scout?'Trust a specialist to improve the odds.':'Requires a healthy, loyal crew member.',cost:job.cost,energy:job.energy+5}
  ];
  return <Modal title="Plan operation" onClose={()=>act({type:'RESOLVE_JOB',approach:'leave'})} className="decision-modal"><div className="dialog-art" style={{backgroundImage:`url(${job.image})`}}><Tag tone="glass">{job.category}</Tag></div><div className="dialog-title"><span className="eyebrow">A WINDOW OF OPPORTUNITY</span><h2>{job.name}</h2><p>{job.description}</p></div><div className="decision-summary"><div><span>Potential take</span><strong>{money(job.reward[0],true)}–{money(job.reward[1],true)}</strong></div><div><span>Heat</span><strong><Fire size={14}/>+{heatGain(state,job.heat)}</strong></div><div><span>Energy</span><strong><Lightning size={14}/>{job.energy}</strong></div></div><div className="choice-list">{approaches.map(p=><button className="choice-card" key={p.id} disabled={state.stats.cash<p.cost||state.stats.energy<p.energy||(p.id==='scout'&&!scout)} onClick={()=>act({type:'RESOLVE_JOB',approach:p.id})}><div className="choice-number">{p.id==='rush'?'01':p.id==='informant'?'02':'03'}</div><div className="choice-copy"><h3>{p.label}</h3><p>{p.text}</p><span className="choice-cost">{money(p.cost)} cost · {p.energy} energy</span></div><div className="choice-chance"><strong>{jobChance(state,job,p.id)}%</strong><span>success</span></div></button>)}</div><div className="decision-risk"><strong>On failure:</strong> preparation and energy are spent, plus:<br/>{failureSummary(extraLoss)}{state.stats.heat+failure.heat!>65&&<><br/>High Heat can also trigger an arrest.</>}</div><button className="choice-leave" onClick={()=>act({type:'RESOLVE_JOB',approach:'leave'})}>Walk away<span>No cost<ArrowRight size={15}/></span></button></Modal>;
}

export function EventDialog({state,act}:ScreenProps){
  const event=events.find(e=>e.id===state.pendingEvent?.id);if(!event)return null;
  return <Modal title={event.title} dismissible={false} className="decision-modal"><div className="dialog-art" style={{backgroundImage:`url(${event.image})`}}><Tag tone="glass">{event.category}</Tag></div><div className="dialog-title"><span className="eyebrow">THE CITY HAS OTHER PLANS.</span><h2>{event.title}</h2><p>{event.text}</p></div><div className="choice-list">{event.choices.map((c,i)=>{const locked=eventChoiceRequirements(state,c).length>0;return <button key={c.id} className="choice-card event-choice" disabled={Boolean(locked)} onClick={()=>act({type:'CHOOSE_EVENT',choiceId:c.id})}><div className="choice-number">0{i+1}</div><div className="choice-copy"><h3>{c.label}</h3><p>{c.description}</p><EffectChips effects={c.effects}/>{c.failure&&<span className="choice-failure">Risk: {failureSummary(c.failure)}</span>}</div>{c.chance!==undefined?<div className="choice-chance"><strong>{eventChance(state,c)}%</strong><span>success</span></div>:<ArrowRight size={17}/>}</button>;})}</div></Modal>;
}

export function ResultDialog({state,act}:ScreenProps){
  const result=state.result;if(!result)return null;
  return <Modal title={result.title} onClose={()=>act({type:'DISMISS_RESULT'})} className="result-modal"><div className="result-art" style={{backgroundImage:`url(${result.image})`}}><div className={`result-symbol ${result.success?'':'failed'}`}>{result.success?<CheckCircle size={39} weight="light"/>:<WarningCircle size={39} weight="light"/>}</div></div><div className="dialog-title"><span className="eyebrow">{result.success?'A MOVE THAT MATTERS':'EVERY MOVE HAS A PRICE'}</span><h2>{result.title}</h2><p>{result.text}</p></div><EffectChips effects={result.effects} large/>{result.effects.skillXp&&<div className="xp-line">{Object.entries(result.effects.skillXp).map(([s,n])=><Tag key={s}>+{n} {skillLabels[s as keyof typeof skillLabels]} XP</Tag>)}</div>}{state.jail&&<div className="custody-note"><LockKey size={18}/>{state.jail.days} days in custody</div>}<Button onClick={()=>act({type:'DISMISS_RESULT'})} className="full-width">Continue<ArrowRight size={16}/></Button></Modal>;
}

export function HeistPlanning({state,act,onClose}:ScreenProps&{onClose:()=>void}){
  const [step,setStep]=useState<'briefing'|'crew'>('briefing');
  const [selected,setSelected]=useState<string[]>(state.crew.filter(id=>(state.crewInjured[id]??0)===0&&(state.crewLoyalty[id]??0)>=35).slice(0,heist.requiredCrew));
  const roster=usePagination(state.crew,8,3);
  const requirements=heistRequirements(state);
  return <Modal title="Major heist planning" onClose={onClose} className="heist-modal">
    <div className="dialog-art" style={{backgroundImage:`url(${heist.image})`}}><Tag tone="glass"><Diamond size={12}/>MAJOR HEIST</Tag></div>
    <div className="dialog-title"><h2>{heist.name}</h2>{step==='briefing'&&<p>{heist.description}</p>}</div>
    <div className="decision-summary"><div><span>Potential take</span><strong>{money(heist.reward[0],true)}–{money(heist.reward[1],true)}</strong></div><div><span>Entry cost</span><strong>{money(heist.cost)}</strong></div><div><span>Total energy</span><strong>52</strong></div></div>
    {step==='briefing'?<>
      <div className="requirements-list"><Requirement met={state.stats.reputation>=heist.requiredRep}>{heist.requiredRep} reputation</Requirement><Requirement met={selected.length>=heist.requiredCrew}>{heist.requiredCrew} healthy, trusted crew</Requirement>{heist.requiredItems.map(id=><Requirement key={id} met={state.inventory.includes(id)}>{items.find(i=>i.id===id)?.name??id}</Requirement>)}</div>
      <div className="heist-stages-preview">{heist.stages.map((s,i)=><div key={s.id}><span>0{i+1}</span><strong>{s.name}</strong></div>)}</div>
      <p className="dialog-footnote">Three successful stages secure the payout. Preparation is paid up front; each stage offers its own approach and escape choices.</p>
      <Button className="full-width" onClick={()=>setStep('crew')}>Choose your crew<ArrowRight size={16}/></Button>
    </>:<>
      <h3 className="dialog-subheading">Crew selection <span>{selected.length}/{heist.requiredCrew}</span></h3>
      <div className="heist-crew-select">{roster.visible.map(id=>{const c=crew.find(p=>p.id===id)!;const unavailable=(state.crewInjured[id]??0)>0||(state.crewLoyalty[id]??0)<35;return <button key={id} aria-pressed={selected.includes(id)} className={selected.includes(id)?'selected':''} disabled={unavailable} onClick={()=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<heist.requiredCrew?[...s,id]:s)}><img src={c.portrait} alt="Fully masked crew"/><div><strong>{c.alias}</strong><span>{unavailable?'Recover health and loyalty':c.role}</span></div><span className="selection-box">{selected.includes(id)&&<CheckCircle size={17}/>}</span></button>;})}</div><Pagination {...roster}/>
      {state.crew.length===0&&<p className="detail-description">Recruit three specialists before committing.</p>}
      <div className="decision-risk"><strong>Failure costs:</strong> −12 Health, −4 crew loyalty and an injured participant. A second failed stage ends the attempt: −25 REP and no payout. All paid fees remain spent.</div>
      <Button className="full-width" disabled={requirements.length>0||selected.length<heist.requiredCrew||Boolean(state.heist?.completed)} onClick={()=>{act({type:'START_HEIST',crewIds:selected});onClose();}}>{state.heist?.completed?'Heist completed':`Commit · ${money(heist.cost)}`}<ArrowRight size={16}/></Button>
      {requirements.length>0&&<p className="requirement-hint">{requirements[0]}</p>}
      <button className="choice-leave" onClick={()=>setStep('briefing')}>Back to briefing<ArrowRight size={15}/></button>
    </>}
  </Modal>;
}

export function HeistStageDialog({state,act}:ScreenProps){
  const stage=state.heist&&!state.heist.completed?heist.stages[state.heist.stage]:null;if(!stage)return null;
  return <Modal title={stage.name} dismissible={false} className="decision-modal"><div className="dialog-art" style={{backgroundImage:`url(${heist.image})`}}><Tag tone="glass">STAGE {state.heist!.stage+1} OF {heist.stages.length}</Tag></div><div className="heist-step-track">{heist.stages.map((s,i)=><span key={s.id} className={i<=state.heist!.stage?'active':''}/>)}</div><div className="dialog-title"><span className="eyebrow">{heist.name.toUpperCase()}</span><h2>{stage.name}</h2><p>{stage.description}</p></div><div className="choice-list">{stage.choices.map((c,i)=><button className="choice-card" key={c.id} disabled={state.stats.cash<c.cost||state.stats.energy<8} onClick={()=>act({type:'HEIST_CHOICE',choiceId:c.id})}><div className="choice-number">0{i+1}</div><div className="choice-copy"><h3>{c.label}</h3><p>{c.description}</p><span className="choice-cost">{money(c.cost)} · 8 energy · +{heatGain(state,c.heat)} Heat</span></div><div className="choice-chance"><strong>{heistChance(state,c.id)}%</strong><span>success</span></div></button>)}</div><div className="decision-risk"><strong>On failure:</strong> −12 Health, −4 crew loyalty, participant injured for 2 days.{state.heist!.stage-state.heist!.successes>0?' Another failure ends the heist: −25 REP, no payout.':' Two failed stages end the heist without a payout.'}</div><button className="choice-leave" onClick={()=>act({type:'ABORT_HEIST'})}>Abort operation<span>−15 REP · +8 Heat<ArrowRight size={15}/></span></button><p className="dialog-footnote">Aborting also costs 8 crew loyalty. Entry and stage fees are not refunded.</p></Modal>;
}

export function DetailDialog({overlay,onClose,...props}:ScreenProps&{overlay:Overlay;onClose:()=>void}){
  const {state,act,nav}=props;if(!overlay)return null;
  if(overlay.kind==='lay-low'||overlay.kind==='clinic'){
    const hide=overlay.kind==='lay-low';const cost=layLowCost(state);
    return <Modal title={hide?'Lay low':'Visit the clinic'} onClose={onClose}><div className="dialog-large-icon">{hide?<MoonStars size={40}/>:<Heart size={40}/>}</div><div className="dialog-title"><h2>{hide?'Let the heat fade.':'Get back on your feet.'}</h2><p>{hide?'Stay out of sight for a while.':'Discreet medical care, paid up front.'}</p></div><EffectChips large effects={hide?{heat:-12,health:Math.min(5,100-state.stats.health),energy:-cost}:{cash:-500,health:Math.min(35,100-state.stats.health)}}/><Button className="full-width" disabled={Boolean(state.jail)||(hide?state.stats.energy<cost:state.stats.cash<500||state.stats.health>=100)} onClick={()=>{act({type:hide?'LAY_LOW':'HEAL'});onClose();}}>{hide?`Lay low · ${cost} energy`:'Visit clinic · $500'}<ArrowRight size={16}/></Button></Modal>;
  }
  if(overlay.kind==='territory'){
    const d=districts.find(entry=>entry.id===overlay.id);if(!d)return null;
    const unavailable=Boolean(state.jail)||state.districtId!==d.id||state.stats.reputation<d.requiredRep||(state.territories[d.id]??0)>=100;
    return <Modal title={`${d.name} influence`} onClose={onClose} className="decision-modal"><div className="dialog-art" style={{backgroundImage:`url(${d.image})`}}><Tag tone="glass">{state.territories[d.id]??0}% TERRITORY</Tag></div><div className="dialog-title"><h2>Make ground in {d.name}.</h2><p>{d.gang} controls the local network. Choose how to expand yours.</p></div><div className="choice-list">{(['negotiate','pressure'] as const).map(mode=>{const peaceful=mode==='negotiate';const cost=influenceCost(state,mode);return <button key={mode} className="choice-card" disabled={unavailable||state.stats.cash<cost||state.stats.energy<(peaceful?15:25)} onClick={()=>{act({type:'INFLUENCE',districtId:d.id,mode});onClose();}}><div className="choice-copy"><h3>{peaceful?'Negotiate an agreement':'Apply pressure'}</h3><span className="choice-cost">{money(cost)} · {peaceful?15:25} energy</span><EffectChips effects={peaceful?{reputation:8,influence:4,heat:-2}:{reputation:12,influence:6,heat:9}}/><span className="choice-cost">+{peaceful?12:18}% territory on success</span></div><div className="choice-chance"><strong>{influenceChance(state,mode,d.id)}%</strong><span>success</span></div></button>;})}</div><div className="decision-risk"><strong>If pressure fails:</strong> fees spent, −12 Health, −5 REP, −5% territory, +9 Heat, −3 crew loyalty and a possible crew injury.</div></Modal>;
  }
  if(overlay.kind==='rest')return <Modal title="End the day" onClose={onClose}><div className="dialog-large-icon"><MoonStars size={40}/></div><div className="dialog-title"><span className="eyebrow">THE CITY NEVER SLEEPS. YOU SHOULD.</span><h2>Call it a night?</h2><p>Restore energy, recover health, and settle your daily ledger.</p></div><div className="rest-ledger"><div><span>Business income</span><strong>+{money(dailyIncome(state))}</strong></div><div><span>Crew salaries</span><strong>−{money(crewSalary(state))}</strong></div><div><span>Net for today</span><strong>{money(dailyIncome(state)-crewSalary(state))}</strong></div></div>{state.jail&&<div className="custody-note"><LockKey size={18}/>{state.jail.days} days left in custody</div>}<p className="dialog-footnote">The city may have a new event waiting in the morning.</p><Button className="full-width" onClick={()=>{act({type:'NEXT_DAY'});onClose();}}>Begin day {state.day+1}<ArrowRight size={16}/></Button></Modal>;
  if(overlay.kind==='help')return <Modal title="Risk guide" onClose={onClose}><div className="dialog-title"><span className="eyebrow">KNOW WHAT YOU'RE RISKING</span><h2>Read the room.</h2></div><div className="guide-list"><div><Fire size={23}/><div><h3>Heat attracts police.</h3><p>At 65+ Heat, investigations can lead to arrest. Laying low and legitimate contacts help.</p></div></div><div><Star size={23}/><div><h3>Your reputation opens doors.</h3><p>Successful jobs and quests unlock districts, specialists, businesses and the major heist.</p></div></div><div><UsersThree size={23}/><div><h3>Loyalty is earned daily.</h3><p>Pay salaries. Protect injured crew. Healthy crew with at least 35% loyalty can scout and join heists.</p></div></div><div><Lightning size={23}/><div><h3>Spend the day wisely.</h3><p>End the day to restore energy and collect income. Training, gear and preparation improve success odds.</p></div></div></div></Modal>;
  if(overlay.kind==='crew'){const c=crew.find(c=>c.id===overlay.id);if(!c)return null;const owned=state.crew.includes(c.id);return <Modal title={c.alias} onClose={onClose}><div className="profile-detail"><img src={c.portrait} alt="Fully masked specialist"/><div><Tag tone="gold">{c.role}</Tag><span className="eyebrow">{c.name}</span><h2>{c.alias}</h2></div></div><p className="detail-description">{c.description}</p><div className="detail-data"><div><span>{skillLabels[c.skill]}</span><strong>{c.rating}/10</strong></div><div><span>Daily salary</span><strong>{money(c.salary)}</strong></div><div><span>Loyalty</span><strong>{state.crewLoyalty[c.id]??c.loyalty}%</strong></div></div><Bar value={state.crewLoyalty[c.id]??c.loyalty} label="Loyalty"/><p className="detail-trait">{c.trait}</p>{owned?<Button variant="secondary" className="full-width" onClick={onClose}>Back to the city<ArrowRight size={16}/></Button>:<Button className="full-width" disabled={state.stats.cash<c.cost||state.stats.reputation<c.requiredRep||Boolean(state.jail)} onClick={()=>{act({type:'RECRUIT',id:c.id});onClose();}}>Recruit · {money(c.cost)}<ArrowRight size={16}/></Button>}</Modal>;}
  if(overlay.kind==='district'){const d=districts.find(d=>d.id===overlay.id);if(!d)return null;return <Modal title={d.name} onClose={onClose}><div className="dialog-art" style={{backgroundImage:`url(${d.image})`}}><Tag tone="glass">{d.subtitle}</Tag></div><div className="dialog-title"><h2>{d.name}</h2><p>{d.description}</p></div><div className="detail-data"><div><span>Rival faction</span><strong>{d.gang}</strong></div><div><span>Your influence</span><strong>{state.territories[d.id]??0}%</strong></div></div><Requirement met={state.stats.reputation>=d.requiredRep}>{d.requiredRep} reputation required</Requirement><Button className="full-width" disabled={state.stats.reputation<d.requiredRep||Boolean(state.jail)} onClick={()=>{if(state.districtId!==d.id)act({type:'TRAVEL',id:d.id});nav('operations');onClose();}}>Find an operation<ArrowRight size={16}/></Button></Modal>;}
  if(overlay.kind==='item'){const item=items.find(i=>i.id===overlay.id);if(!item)return null;const owned=state.inventory.includes(item.id);return <Modal title={item.name} onClose={onClose}><div className="item-detail-art"><img src={item.image} alt={item.name}/></div><div className="dialog-title"><Tag>{item.category}</Tag><h2>{item.name}</h2><p>{item.description}</p></div><div className="item-bonuses">{Object.entries(item.bonuses).map(([key,value])=><Tag tone="gold" key={key}>+{value} {key==='heatReduction'?'Heat protection':key==='health'?'Health':key==='energy'?'Energy':skillLabels[key as keyof typeof skillLabels]}</Tag>)}</div><Requirement met={state.stats.reputation>=item.requiredRep}>{item.requiredRep} reputation</Requirement><Button className="full-width" disabled={(owned&&!item.consumable)||state.stats.cash<item.cost||state.stats.reputation<item.requiredRep||Boolean(state.jail)} onClick={()=>{act({type:'BUY_ITEM',id:item.id});onClose();}}>{owned&&!item.consumable?'Already in your inventory':`${item.consumable?'Use':'Acquire'} · ${money(item.cost)}`}<ArrowRight size={16}/></Button></Modal>;}
  if(overlay.kind==='contact'){
    const c=contacts.find(c=>c.id===overlay.id);if(!c)return null;
    const trust=state.relationships[c.id]??c.initialRelationship;
    const unavailable=state.stats.reputation<c.requiredRep||Boolean(state.jail&&!['vale','mara'].includes(c.id));
    return <Modal title={c.name} onClose={onClose}><div className="profile-detail"><img src={c.portrait} alt="Fully masked contact"/><div><Tag>{c.role}</Tag><h2>{c.name}</h2><span>{trust}% trust</span></div></div><p className="detail-description">{c.description}</p><Bar value={trust} label="Relationship"/><Requirement met={state.stats.reputation>=c.requiredRep}>{c.requiredRep} reputation required</Requirement><div className="choice-list contact-decisions">{(['favor','gift'] as const).map(mode=>{const effects=contactEffects(state,c.id,mode);return <button key={mode} className="choice-card" disabled={unavailable||(mode==='favor'?state.stats.energy<15:state.stats.cash<contactCost(state,c.id,mode))} onClick={()=>{act({type:'CONTACT',id:c.id,mode});onClose();}}><div className="choice-copy"><h3>{mode==='favor'?'Do a favor':'Send a gift'}</h3><EffectChips effects={effects}/>{effects.skillXp&&<span className="choice-cost">+15 Charisma XP</span>}</div><ArrowRight size={18}/></button>;})}</div></Modal>;
  }
  return null;
}

export function JailBanner({state,act,open}:ScreenProps){if(!state.jail)return null;return <div className="jail-banner"><LockKey size={22}/><div><strong>In custody · {state.jail.days} days remaining</strong><span>{state.jail.reason}</span></div><Button variant="secondary" disabled={state.stats.cash<bailCost(state)} onClick={()=>act({type:'BAIL'})}>Post bail · {money(bailCost(state))}</Button><button className="text-link" onClick={()=>open({kind:'rest'})}>Serve time<ArrowRight size={15}/></button></div>;}
