import { useState } from 'react';
import { ArrowRight, CheckCircle, FlagCheckered, LockKey, Target } from '@phosphor-icons/react';
import { quests } from '../data';
import { questProgress } from '../game/engine';
import type { Quest } from '../game/types';
import type { Screen, ScreenProps } from './view-types';
import { Bar, Button, money, Pagination, Tabs, Tag, usePagination } from './components';

function questDestination(q:Quest):Screen{return q.metric==='crew'?'crew':q.metric==='businesses'?'empire':q.metric==='items'||q.metric==='training'?'character':q.metric==='influence'||q.metric==='districts'?'city':'operations';}
export function Journal({state,act,nav}:ScreenProps){
  const [tab,setTab]=useState('main');const [filter,setFilter]=useState('active');
  const list=quests.filter(q=>q.kind===tab&&(filter==='completed'?state.claimedQuests.includes(q.id):!state.claimedQuests.includes(q.id)));
  const pagination=usePagination(list,4,2,tab+filter);const chronicle=usePagination(state.log,7,4);
  return <><div className="page-heading"><div><span className="eyebrow">EVERY CHOICE LEAVES A MARK.</span><h1>Your story.</h1><p>From a name on the street to a name above the city.</p></div><FlagCheckered size={30} className="heading-icon"/></div><Tabs options={[{id:'main',label:'Main story'},{id:'side',label:'Side quests'},{id:'chronicle',label:'Chronicle'}]} value={tab} onChange={setTab}/>{tab!=='chronicle'&&<><div className="filter-chips">{['active','completed'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='active'?'In progress':'Completed'}</button>)}</div><div className="quest-list">{pagination.visible.map(q=>{const claimed=state.claimedQuests.includes(q.id);const unlocked=!q.prerequisite||state.claimedQuests.includes(q.prerequisite);const progress=Math.min(questProgress(state,q),q.target);const complete=progress>=q.target;return <article className={`quest-card ${!unlocked?'locked':''}`} key={q.id}><div className="quest-card-mark">{claimed?<CheckCircle size={23}/>:!unlocked?<LockKey size={21}/>:<Target size={23}/>}</div><div className="quest-card-copy"><span className="eyebrow">{q.chapter??q.contact}</span><h3>{q.name}</h3><p>{q.description}</p><div className="quest-progress"><Bar value={progress} max={q.target} label={q.name}/><span>{progress}/{q.target}</span></div><div className="quest-rewards">{q.reward.cash&&<Tag tone="gold">+{money(q.reward.cash)}</Tag>}{q.reward.reputation&&<Tag>+{q.reward.reputation} REP</Tag>}{q.reward.influence&&<Tag>+{q.reward.influence} influence</Tag>}</div></div><div className="quest-card-action">{claimed?<Tag tone="gold">CLAIMED</Tag>:!unlocked?<span className="small muted">Earlier chapter required</span>:complete?<Button onClick={()=>act({type:'CLAIM_QUEST',id:q.id})}>Claim reward<ArrowRight size={14}/></Button>:<button className="icon-button" aria-label={`Continue ${q.name}`} onClick={()=>nav(questDestination(q))}><ArrowRight size={20}/></button>}</div></article>;})}</div>{list.length===0&&<div className="empty-state"><FlagCheckered size={30}/><h3>{filter==='completed'?'Your legacy starts here.':'All caught up.'}</h3><p>{filter==='completed'?'Complete a quest and claim its reward.':'Explore the city for your next opportunity.'}</p></div>}<Pagination {...pagination}/></>}{tab==='chronicle'&&<><div className="chronicle-list">{chronicle.visible.map((entry,i)=><article className="chronicle-row" key={`${entry.day}-${i}`}><span className="chronicle-day">D{String(entry.day).padStart(2,'0')}</span><div><h3>{entry.title}</h3><p>{entry.text}</p></div><span className={`chronicle-dot ${entry.good?'good':''}`}/></article>)}</div>{state.log.length===0&&<div className="empty-state"><h3>A clean page.</h3><p>Your choices will write the next entry.</p></div>}<Pagination {...chronicle}/></>}</>;
}
