import { ArrowRight, CheckCircle, Crown, Lightning, Play, ShieldCheck, Wallet } from '@phosphor-icons/react';
import type { MonetizationSnapshot, RewardedPlacement } from '../services/monetization';
import { strategySummary } from '../game/strategy';
import type { GameState } from '../game/types';
import { Button, Modal, Tag } from './components';

export function RemoveAdsDialog({ status, onClose, onBuy, onRestore, onPrivacy }: { status: MonetizationSnapshot; onClose: () => void; onBuy: () => void; onRestore: () => void; onPrivacy: () => void }) {
  return <Modal title="Remove ads" onClose={onClose} className="strategy-modal remove-ads-modal"><div className="premium-emblem"><img src="/assets/icon-192.png" alt="BLACKLINE emblem" /><Crown size={28} /></div><div className="strategy-dialog-heading"><span className="eyebrow">THE UNINTERRUPTED EDITION</span><h2>{status.removeAds ? 'Your city. No interruptions.' : 'Keep the city yours.'}</h2><p>A one-time purchase. Every future chapter stays with you.</p></div><div className="premium-benefits"><div><CheckCircle size={20} /><span>No banner ads</span></div><div><CheckCircle size={20} /><span>No interstitial breaks</span></div><div><CheckCircle size={20} /><span>Daily supplies without rewarded videos</span></div></div>{status.removeAds ? <div className="premium-owned"><ShieldCheck size={24} /><strong>REMOVE ADS IS ACTIVE</strong><span>Active on this device.</span></div> : <><div className="premium-price"><strong>{status.price ?? 'US$4.99'}</strong><span>ONE-TIME · NO SUBSCRIPTION</span></div><Button className="full-width" disabled={!status.nativeSupported || !status.price || status.busy} onClick={onBuy}>{status.busy ? 'Connecting to Google Play…' : status.nativeSupported && status.price ? `Buy · ${status.price}` : 'Available on Google Play'}<ArrowRight size={18} /></Button><p className="store-availability">{!status.nativeSupported ? 'Purchase from the Android app through Google Play.' : !status.price ? 'Connect through Google Play to view the local price and purchase.' : 'Google Play confirms the price before you pay.'}</p></>}<Button variant="secondary" className="full-width restore-purchases" disabled={!status.nativeSupported || status.busy} onClick={onRestore}>Restore purchases<ArrowRight size={16} /></Button>{status.error && <p className="store-status" role="status">{status.error}</p>}{status.privacyRequired && <button className="text-link store-privacy" onClick={onPrivacy}>Privacy choices<ArrowRight size={14} /></button>}</Modal>;
}

export function SuppliesDialog({ state, status, onClose, onClaim, onStore }: { state: GameState; status: MonetizationSnapshot; onClose: () => void; onClaim: (kind: RewardedPlacement) => void; onStore: () => void }) {
  const summary = strategySummary(state);
  const canEarn = status.removeAds || (status.nativeSupported && status.rewardedReady);
  const offerings = [{ kind: 'energy' as const, label: 'Catch your breath.', amount: '+20 energy', remaining: summary.rewardEnergyRemaining, full: state.stats.energy >= 100, icon: Lightning }, { kind: 'cash' as const, label: 'An extra envelope.', amount: '+$500 cash', remaining: summary.rewardCashRemaining, full: false, icon: Wallet }];
  return <Modal title="Daily supplies" onClose={onClose} className="strategy-modal supplies-modal"><div className="strategy-dialog-heading"><span className="eyebrow">A LITTLE ROOM TO MANEUVER</span><h2>Daily supplies.</h2><p>{status.removeAds ? 'Your supply allowance is ready. No video required.' : 'Optional rewarded videos. Your story always remains playable offline.'}</p></div><div className="supply-options">{offerings.map(offer => <article key={offer.kind}><div className="supply-heading"><offer.icon size={26} /><Tag tone="gold">{offer.amount}</Tag></div><h3>{offer.label}</h3><p>{offer.remaining > 0 ? `${offer.remaining} claim${offer.remaining === 1 ? '' : 's'} left this game day` : 'Returns after you end the day'}</p><Button className="full-width" variant="secondary" disabled={!canEarn || status.busy || offer.remaining === 0 || offer.full || Boolean(state.jail)} onClick={() => onClaim(offer.kind)}>{offer.full ? 'Energy is full' : offer.remaining === 0 ? 'Claimed today' : status.busy ? 'Please wait…' : status.removeAds ? 'Claim supply' : status.rewardedReady ? <><Play size={17} />Watch & claim</> : 'Video unavailable'}<ArrowRight size={16} /></Button></article>)}</div>{!status.removeAds && <button className="supplies-upgrade" onClick={onStore}><Crown size={20} /><span>Remove ads · {status.price ?? 'US$4.99'}</span><ArrowRight size={16} /></button>}<p className="dialog-footnote">{status.removeAds ? 'Daily limits reset on game days.' : 'A reward is granted only after a completed video. Daily limits reset on game days.'}</p></Modal>;
}
