import { useState } from 'react';
import { ArrowRight, Crosshair, Lightning, LockKey, MagnifyingGlass, MapPin, Fire, Diamond } from '@phosphor-icons/react';
import { activities, districts, heist } from '../data';
import { jobChance, jobRequirements } from '../game/engine';
import type { ScreenProps } from './view-types';
import { EmptyState, money, Pagination, Tag, usePagination } from './components';

export function Operations({state,act,open}:ScreenProps) {
  const [category,setCategory]=useState('all'); const [search,setSearch]=useState('');
  const local=activities.filter(a=>a.districtId===state.districtId);
  const choices=['all',...new Set(local.map(a=>a.category))];
  const filtered=local.filter(a=>(category==='all'||a.category===category)&&a.name.toLowerCase().includes(search.toLowerCase()));
  const pagination=usePagination(filtered,6,2,category+search+state.districtId);
  return <><div className="page-heading"><div><span className="eyebrow">RISK SOMETHING. BECOME SOMEONE.</span><h1>Make your move.</h1><p>The next score is a choice away.</p></div><Crosshair size={30} className="heading-icon"/></div><div className="operations-toolbar"><div className="district-select"><MapPin size={17}/><select aria-label="Operation district" value={state.districtId} onChange={e=>{setCategory('all');act({type:'TRAVEL',id:e.target.value});}}>{districts.map(d=><option key={d.id} value={d.id} disabled={state.stats.reputation<d.requiredRep}>{d.name}{state.stats.reputation<d.requiredRep?` · ${d.requiredRep} REP`:''}</option>)}</select></div><label className="search-field"><MagnifyingGlass size={16}/><input aria-label="Search operations" placeholder="Find a score" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="filter-chips">{choices.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c==='all'?'All operations':c}</button>)}</div><div className="mission-grid">{pagination.visible.map(a=>{const requirements=jobRequirements(state,a);return <article className="mission-card" key={a.id}><div className="mission-card-art" style={{backgroundImage:`url(${a.image})`}}><Tag tone="glass">{a.category}</Tag>{a.requiredRep>state.stats.reputation&&<LockKey size={20}/>}</div><div className="mission-card-body"><div className="mission-card-title"><h3>{a.name}</h3><span className="chance-pill">{jobChance(state,a)}%</span></div><div className="job-difficulty"><span>{a.difficulty<=2?'Low':a.difficulty<=4?'Medium':'High'} risk</span><div>{Array.from({length:5},(_,i)=><i key={i} className={i<Math.ceil(a.difficulty/2)?'filled':''}/>)}</div></div><div className="job-values"><strong>{money(a.reward[0],true)}–{money(a.reward[1],true)}</strong><span><Lightning size={13}/>{a.energy}</span><span><Fire size={13}/>+{a.heat}</span></div><div className="job-footer"><span>{requirements[0]??`${money(a.cost)} prep`}</span><button className="mini-button" disabled={requirements.length>0} onClick={()=>act({type:'START_JOB',id:a.id})}>Plan<ArrowRight size={14}/></button></div></div></article>;})}</div>{filtered.length===0&&<EmptyState title="No leads here" text="Try a different operation or category."/>}<Pagination {...pagination}/><button className="heist-banner" onClick={()=>open({kind:'heist'})} style={{backgroundImage:`linear-gradient(90deg,rgba(15,16,17,.96),rgba(15,16,17,.25)),url(${heist.image})`}}><div className="heist-emblem"><Diamond size={25}/></div><div><span className="eyebrow">THE MAJOR OPERATION</span><h3>{heist.name}</h3><p>{money(heist.reward[0],true)}–{money(heist.reward[1],true)} · {heist.stages.length} stages</p></div><div className="heist-banner-action">{state.stats.reputation<heist.requiredRep?<><LockKey size={16}/>{heist.requiredRep} REP</>:<>View plan<ArrowRight size={16}/></>}</div></button></>;
}
