import { ArrowRight, ArrowUpRight, Bank, CalendarBlank, Crown, Fire, Heart, Lightning, MapPin, MoonStars, ShieldCheck, Star, Target, UsersThree, Wallet } from '@phosphor-icons/react';
import { activities, crew, districts, quests } from '../data';
import { dailyIncome, crewSalary, jobChance, layLowCost, questProgress, rankFor } from '../game/engine';
import type { ScreenProps } from './view-types';
import { AnimatedNumber, Bar, Button, money, SectionTitle, Tag } from './components';

export function Overview({ state, act, nav, open }: ScreenProps) {
  const district = districts.find(d => d.id === state.districtId)!;
  const opportunity = activities.find(a => a.id === 'old-warehouse' && a.districtId === state.districtId) ?? activities.filter(a => a.districtId === state.districtId && a.requiredRep <= state.stats.reputation).at(-1)!;
  const quest = quests.find(q => q.kind === 'main' && !state.claimedQuests.includes(q.id) && (!q.prerequisite || state.claimedQuests.includes(q.prerequisite)));
  const net = dailyIncome(state) - crewSalary(state);
  const stats = [
    { label: 'Cash', value: state.stats.cash, icon: Wallet, cash: true, hint: 'Available balance' },
    { label: 'Reputation', value: state.stats.reputation, icon: Star, hint: rankFor(state.stats.reputation) },
    { label: 'Heat', value: state.stats.heat, icon: Fire, hint: state.stats.heat >= 65 ? 'Under investigation' : state.stats.heat >= 35 ? 'On their radar' : 'Under the radar' },
    { label: 'Influence', value: state.stats.influence, icon: Crown, hint: 'Your city standing' }
  ];
  return <>
    <div className="page-heading overview-heading"><div><span className="eyebrow">YOUR STORY. YOUR RULES.</span><h1>The city is yours.</h1></div><button className="day-pill" onClick={() => open({kind:'rest'})}><CalendarBlank size={17} /><span>Day {String(state.day).padStart(2, '0')}</span><ArrowRight size={15} /></button></div>
    <div className="stats-grid">{stats.map(s => <div className={`stat-card ${s.label === 'Heat' && s.value >= 50 ? 'danger-stat' : ''}`} key={s.label}><div className="stat-label"><s.icon size={17} /><span>{s.label}</span></div><strong><AnimatedNumber value={s.value} currency={s.cash} compact={s.cash && s.value > 99999} /></strong><span className="stat-hint">{s.hint}</span>{s.label === 'Heat' && <Bar value={s.value} tone="heat" label="Heat" />}</div>)}</div>
    <div className="mobile-vitals"><div><Heart size={14} /><span>Health</span><Bar value={state.stats.health} label="Health" /><strong>{state.stats.health}</strong></div><div><Lightning size={14} /><span>Energy</span><Bar value={state.stats.energy} label="Energy" /><strong>{state.stats.energy}</strong></div></div>
    <div className="city-hero" style={{backgroundImage:`url(${district.image})`}}><div className="hero-top"><Tag tone="glass"><MapPin size={12} />{district.name}</Tag><span className="hero-caption">BLACKWATER CITY</span></div><div className="hero-bottom"><div><span className="eyebrow">WHERE IT ALL BEGINS</span><h2>Every empire starts<br />on these streets.</h2></div><button className="hero-explore" onClick={() => nav('city')}>Explore city<ArrowUpRight size={18} /></button></div></div>
    <div className="overview-content"><div className="opportunity-area"><SectionTitle title="Tonight's opportunity" action="All operations" onAction={() => nav('operations')} />{opportunity && <div className="featured-mission"><div className="featured-art" style={{backgroundImage:`url(${opportunity.image})`}}><Tag tone="glass">{opportunity.category}</Tag></div><div className="featured-body"><div className="mission-topline"><Tag tone="gold">HIGH REWARD</Tag><span className="muted small">{opportunity.difficulty <= 2 ? 'Low' : opportunity.difficulty <= 4 ? 'Medium' : 'High'} risk</span></div><h3>{opportunity.name}</h3><p>{opportunity.description}</p><div className="mission-metrics"><div><span>Potential take</span><strong>{money(opportunity.reward[0],true)}–{money(opportunity.reward[1],true)}</strong></div><div><span>Success</span><strong>{jobChance(state,opportunity)}%</strong></div><div><span>Energy</span><strong><Lightning size={13} weight="fill" />{opportunity.energy}</strong></div></div><Button onClick={() => act({type:'START_JOB',id:opportunity.id})} disabled={Boolean(state.jail)}>Plan operation<ArrowRight size={16} /></Button></div></div>}</div>
    <div className="quest-area"><SectionTitle title="Your next chapter" action="Quest journal" onAction={() => nav('journal')} />{quest && <button className="quest-preview" onClick={() => nav('journal')}><div className="quest-mark"><Target size={23} /></div><div className="quest-preview-copy"><span className="eyebrow">{quest.chapter ?? 'MAIN STORY'}</span><h3>{quest.name}</h3><p>{quest.description}</p><div className="quest-progress"><Bar value={Math.min(questProgress(state,quest),quest.target)} max={quest.target} label={quest.name} /><span>{Math.min(questProgress(state,quest),quest.target)} / {quest.target}</span></div></div><ArrowUpRight size={17} className="quest-arrow" /></button>}<div className="quick-actions"><button onClick={() => open({kind:'rest'})}><MoonStars size={19} /><span>End day</span></button><button onClick={() => open({kind:'lay-low'})} disabled={state.stats.energy < layLowCost(state) || Boolean(state.jail)}><ShieldCheck size={19} /><span>Lay low</span></button><button onClick={() => open({kind:'clinic'})} disabled={state.stats.cash < 500 || state.stats.health >= 100}><Heart size={19} /><span>Clinic</span></button></div></div></div>
    <div className="overview-bottom"><div><Bank size={20} /><span>Daily income</span><strong>{net < 0 ? '−' : '+'}{money(Math.abs(net))}</strong><button className="text-link" onClick={() => nav('empire')}>Manage<ArrowRight size={14} /></button></div><div><UsersThree size={20} /><span>Your crew</span><div className="tiny-portraits">{(state.crew.length ? state.crew.map(id => crew.find(c => c.id === id)!).slice(0,3) : crew.slice(0,3)).map(c => <img src={c.portrait} alt={c.alias} key={c.id} />)}</div><button className="text-link" onClick={() => nav('crew')}>{state.crew.length || 'Recruit'}<ArrowRight size={14} /></button></div></div>
  </>;
}

export function IntelPanel({ state, nav, open }: ScreenProps) {
  const availableCrew = crew.filter(c => c.requiredRep <= state.stats.reputation && !state.crew.includes(c.id)).slice(0,2);
  return <aside className="intel-panel"><div className="intel-profile"><button onClick={() => nav('character')} className="profile-avatar"><img src={state.player.portrait} alt="Your masked character" /></button><div><Tag tone="gold">{rankFor(state.stats.reputation)}</Tag><h3>{state.player.name}</h3><p>{state.player.path === 'leader' ? 'Gang leader' : state.player.path === 'boss' ? 'Future crime boss' : state.player.path.charAt(0).toUpperCase()+state.player.path.slice(1)}</p></div></div><div className="vitals"><div><span><Heart size={15} />Health</span><strong>{state.stats.health}<small>/100</small></strong></div><Bar value={state.stats.health} label="Health" /><div><span><Lightning size={15} />Energy</span><strong>{state.stats.energy}<small>/100</small></strong></div><Bar value={state.stats.energy} label="Energy" /></div><div className="intel-block"><div className="intel-title"><Fire size={18} /><h3>Police attention</h3><span className={`status-dot ${state.stats.heat >= 65 ? 'danger' : ''}`} /></div><div className="heat-meter">{Array.from({length:10},(_,i) => <span key={i} className={i < Math.ceil(state.stats.heat/10) ? 'lit' : ''} />)}</div><p>{state.stats.heat >= 65 ? 'An investigation is building. Reduce your Heat.' : state.stats.heat >= 35 ? 'Patrols are watching your district.' : 'A quiet name is a valuable asset.'}</p><button className="text-link" onClick={() => open({kind:'help'})}>View risk guide<ArrowRight size={14} /></button></div><div className="intel-block"><div className="intel-title"><Bank size={18} /><h3>Daily ledger</h3></div><div className="ledger-row"><span>Business income</span><strong>{money(dailyIncome(state))}</strong></div><div className="ledger-row"><span>Crew salaries</span><strong>−{money(crewSalary(state))}</strong></div><div className="ledger-row ledger-total"><span>Net per day</span><strong>{money(dailyIncome(state)-crewSalary(state))}</strong></div><button className="text-link" onClick={() => nav('empire')}>Build your empire<ArrowRight size={14} /></button></div><div className="intel-block recruit-block"><div className="intel-title"><UsersThree size={18} /><h3>{state.crew.length ? 'Grow your circle' : 'Talent on the street'}</h3></div>{availableCrew.map(c => <button className="talent-row" key={c.id} onClick={() => open({kind:'crew',id:c.id})}><img src={c.portrait} alt="Masked recruit" /><div><strong>{c.alias}</strong><span>{c.role}</span></div><ArrowUpRight size={15} /></button>)}<button className="text-link" onClick={() => nav('crew')}>Meet the crew<ArrowRight size={14} /></button></div><div className="intel-quote"><span className="quote-rule" /><p>“You don't need to own the streets.<br />Just the people who do.”</p><span>THE BLACKWATER CODE</span></div></aside>;
}
