import { useState } from 'react';
import { ArrowRight, Crosshair, Lightning, Shield, ShieldWarning, UsersThree } from '@phosphor-icons/react';
import { crew, districts, items, operations, rivals, zones } from '../data';
import { battleChoiceInfo, battlePreview, getStrategy, operationChoiceInfo, operationEntryInfo, rivalTruceInfo, strategySummary, zoneActionInfo, zoneView } from '../game/strategy';
import type { BattleApproach, BattleChoiceId, CommandInfo, ZoneActionMode } from '../game/strategy-types';
import type { GameState } from '../game/types';
import type { ScreenProps } from './view-types';
import { Bar, Button, Modal, money, Pagination, Tag, Tabs, usePagination } from './components';

function Gate({ reasons }: { reasons: string[] }) {
  return reasons.length > 0 ? <p className="action-gate" role="status"><ShieldWarning size={17} /><span>{reasons[0]}{reasons.length > 1 && <small> · {reasons.length - 1} more requirements</small>}</span></p> : null;
}

function ResourcePreview({ info, chanceLabel = 'Success chance' }: { info: CommandInfo; chanceLabel?: string }) {
  return <div className="strategy-preview"><div><span>Cash committed</span><strong>{money(info.cost)}</strong></div><div><span>Energy</span><strong><Lightning size={16} />{info.energy}</strong></div><div><span>{chanceLabel}</span><strong className="gold-text">{info.chance}%</strong></div></div>;
}

export function CrewSelection({ state, selected, onChange, maximum = 3 }: { state: GameState; selected: string[]; onChange: (next: string[]) => void; maximum?: number }) {
  const strategy = getStrategy(state), ready = strategySummary(state).activeCrewIds;
  const members = state.crew.map(id => crew.find(c => c.id === id)!).filter(Boolean);
  const pages = usePagination(members, 4, 4);
  return <div className="crew-selection"><div className="strategy-section-title"><strong><UsersThree size={17} />Choose your crew</strong><Tag>{selected.length} / {maximum}</Tag></div>{members.length === 0 ? <div className="strategy-empty"><UsersThree size={25} /><p>Recruit specialists from the Crew screen first.</p></div> : <><div className="crew-select-grid">{pages.visible.map(member => {
    const chosen = selected.includes(member.id), available = ready.includes(member.id);
    return <button key={member.id} className={`crew-select-button ${chosen ? 'selected' : ''}`} aria-label={`Select ${member.alias}`} aria-pressed={chosen} disabled={!available || (!chosen && selected.length >= maximum)} onClick={() => onChange(chosen ? selected.filter(id => id !== member.id) : [...selected, member.id])}><img src={member.portrait} alt="Opaque masked crew member" /><div><strong>{member.alias}</strong><span>{member.role} · {member.rating}</span><small>{!available ? (state.crewInjured[member.id] ?? 0) > 0 ? 'Recovering' : (state.crewLoyalty[member.id] ?? 0) < 35 ? 'Low loyalty' : 'Assigned / exhausted' : `${strategy.crewFatigue[member.id] ?? 0}% fatigue`}</small></div><i aria-hidden="true">{chosen ? '✓' : '+'}</i></button>;
  })}</div><Pagination {...pages} /></>}</div>;
}

export function ZoneCommand({ state, act, open, id, onClose }: ScreenProps & { id: string; onClose: () => void }) {
  const [tab, setTab] = useState('actions');
  const view = zoneView(state, id);
  if (!view) return null;
  const district = districts.find(d => d.id === view.definition.districtId)!;
  const actionLabels: Record<ZoneActionMode, string> = { scout: 'Scout zone', negotiate: view.owned ? 'Restore control' : 'Negotiate control', disrupt: 'Disrupt rival income', fortify: 'Fortify zone' };
  const actionDescriptions: Record<ZoneActionMode, string> = { scout: 'Better intel improves the opening odds.', negotiate: view.owned ? 'Secure the ground your crew has already won.' : 'Build a foothold without a crew battle.', disrupt: 'Reduce rival strength and provoke a response.', fortify: 'Stronger defenses help hold the next day.' };
  return <Modal title="Zone command" onClose={onClose} className="strategy-modal zone-command-modal"><div className="strategy-dialog-heading"><Tag tone="gold">{district.name}</Tag><h2>{view.definition.name}</h2><p>{view.definition.description}</p></div><div className="zone-command-ledger"><div><span>Control</span><strong>{view.state.control}%</strong></div><div><span>Intel</span><strong>{view.state.intel}%</strong></div><div><span>Daily net</span><strong>{money(view.income - view.upkeep)}</strong></div></div><Tabs options={[{ id: 'actions', label: 'Actions' }, { id: 'defense', label: 'Defense' }]} value={tab} onChange={setTab} />
    {tab === 'actions' ? <><div className="strategy-choice-list">{(view.owned ? ['scout', 'negotiate', 'fortify'] : ['scout', 'negotiate', 'disrupt'] as ZoneActionMode[]).map(mode => {
      const typedMode = mode as ZoneActionMode, info = zoneActionInfo(state, id, typedMode);
      return <button key={mode} className="strategy-choice" aria-label={`${actionLabels[typedMode]} · ${money(info.cost)} · ${info.energy} energy`} disabled={info.requirements.length > 0} title={info.requirements.join(' ')} onClick={() => act({ type: 'ZONE_ACTION', zoneId: id, mode: typedMode })}><div><strong>{actionLabels[typedMode]}<span>{info.chance}%</span></strong><p>{actionDescriptions[typedMode]}</p><small>{info.requirements[0] ?? info.consequence}</small><div className="choice-resource-line"><span>{money(info.cost)}</span><span><Lightning size={14} />{info.energy}</span></div></div><ArrowRight size={19} /></button>;
    })}</div>{!view.owned && <Button variant="secondary" className="full-width" onClick={() => open({ kind: 'battle-plan', id })}><Crosshair size={18} />Plan a crew attack<ArrowRight size={17} /></Button>}</> : <><div className="defense-summary"><Shield size={27} /><div><strong>{view.defense} defense rating</strong><p>{view.connected ? 'Connected to your Market Street foothold.' : 'Isolated ground earns less and is harder to hold.'}</p></div></div><p className="section-note">A lieutenant helps defend this zone and stays out of attacks and major operations while assigned.</p>{!view.owned ? <Gate reasons={['Capture this zone before assigning a lieutenant.']} /> : <><label className="strategy-select-label" htmlFor="lieutenant-choice">Zone lieutenant</label><select id="lieutenant-choice" aria-label="Zone lieutenant" className="strategy-select" value={view.state.lieutenantId ?? ''} onChange={e => act({ type: 'ASSIGN_LIEUTENANT', zoneId: id, crewId: e.target.value || null })}><option value="">Unassigned</option>{state.crew.map(crewId => { const member = crew.find(c => c.id === crewId)!; const occupied = Object.entries(getStrategy(state).zones).some(([zoneId, zone]) => zoneId !== id && zone.lieutenantId === crewId); return <option key={crewId} value={crewId} disabled={occupied || (state.crewInjured[crewId] ?? 0) > 0 || (state.crewLoyalty[crewId] ?? 0) < 35}>{member.alias} · {member.role}{occupied ? ' · assigned elsewhere' : ''}</option>; })}</select><div className="defense-cost"><span>Fortifications</span><strong>{view.state.fortification} / 3</strong><span>Upkeep per day</span><strong>{money(view.upkeep)}</strong></div></>}</>}
  </Modal>;
}

export function RivalDiplomacy({ state, act, id, onClose }: ScreenProps & { id: string; onClose: () => void }) {
  const rival = rivals.find(r => r.id === id);
  if (!rival) return null;
  const current = getStrategy(state).rivals[id], info = rivalTruceInfo(state, id), truce = current.truceUntil > state.day;
  return <Modal title="Rival diplomacy" onClose={onClose} className="strategy-modal"><div className="dialog-art compact-strategy-art" style={{ backgroundImage: 'url(/assets/underworld-conflict.webp)' }}><Tag tone="glass">{districts.find(d => d.id === rival.districtId)?.name}</Tag></div><div className="strategy-dialog-heading"><h2>{rival.name}</h2><p>{rival.description}</p></div><div className="strategy-preview"><div><span>Strength</span><strong>{current.strength}</strong></div><div><span>Hostility</span><strong>{current.hostility}%</strong></div><div><span>Alert</span><strong>{current.alert}%</strong></div></div><div className="diplomacy-terms"><Shield size={25} /><div><strong>{truce ? 'An agreement is in force.' : `${info.duration} days to breathe.`}</strong><p>{truce ? `The truce expires on day ${current.truceUntil}. Neither side can attack or disrupt during its term.` : info.consequence}</p></div></div>{!truce && <><ResourcePreview info={info} /><Gate reasons={info.requirements} /></>}<Button className="full-width" variant={truce ? 'secondary' : 'primary'} disabled={truce || info.requirements.length > 0} onClick={() => act({ type: 'RIVAL_TRUCE', rivalId: id })}>{truce ? `${current.truceUntil - state.day} days remaining` : `Negotiate truce · ${money(info.cost)}`}<ArrowRight size={18} /></Button></Modal>;
}

export function BattlePlanning({ state, act, id, onClose }: ScreenProps & { id: string; onClose: () => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const [approach, setApproach] = useState<BattleApproach>('balanced');
  const zone = zones.find(z => z.id === id);
  if (!zone) return null;
  const info = battlePreview(state, id, selected, approach);
  return <Modal title="Plan zone attack" onClose={onClose} className="strategy-modal"><div className="dialog-art compact-strategy-art" style={{ backgroundImage: 'url(/assets/underworld-conflict.webp)' }}><Tag tone="glass">THREE ROUNDS · TERRITORY DISPUTE</Tag></div><div className="strategy-dialog-heading"><span className="eyebrow">COMMIT YOUR CREW</span><h2>{zone.name}</h2></div><CrewSelection state={state} selected={selected} onChange={setSelected} maximum={3} /><div className="battle-approaches" aria-label="Attack approach">{([{ id: 'silent', label: 'Silent', text: 'Lower exposure' }, { id: 'balanced', label: 'Measured', text: 'Steady momentum' }, { id: 'force', label: 'Force', text: 'More momentum' }] as const).map(option => <button key={option.id} aria-pressed={approach === option.id} onClick={() => setApproach(option.id)} className={approach === option.id ? 'selected' : ''}><strong>{option.label}</strong><span>{option.text}</span></button>)}</div><ResourcePreview info={info} chanceLabel="Opening odds" /><p className="attack-balance">Your strength <strong>{info.power}</strong><span>vs.</span> Rival defense <strong>{info.defense}</strong></p><Gate reasons={info.requirements} /><Button className="full-width" disabled={info.requirements.length > 0} onClick={() => { act({ type: 'START_BATTLE', zoneId: id, crewIds: selected, approach }); onClose(); }}>Commit to attack<ArrowRight size={18} /></Button><p className="dialog-footnote">Injuries, fatigue and rival retaliation can outlast the encounter.</p></Modal>;
}

export function BattleEncounter({ state, act }: ScreenProps) {
  const battle = getStrategy(state).battle;
  if (!battle) return null;
  const zone = zones.find(z => z.id === battle.zoneId)!;
  const candidates: BattleChoiceId[] = ['advance', 'flank', 'cover', ...(battle.morale < 65 ? ['rally' as const] : [])];
  const retreat = battleChoiceInfo(state, 'retreat');
  return <Modal title="Territory battle" dismissible={false} className="strategy-modal encounter-modal"><div className="dialog-art compact-strategy-art" style={{ backgroundImage: 'url(/assets/underworld-conflict.webp)' }}><Tag tone="glass">ROUND {battle.round + 1} / 3</Tag><span className="encounter-badge"><Crosshair size={18} />TACTICAL DECISION</span></div><div className="strategy-dialog-heading"><h2>{zone.name}</h2><p>{battle.round === 0 ? 'The rival holds its line. Choose how your crew opens.' : battle.round === 1 ? 'Both sides adapt. Protect your crew or press the advantage.' : 'The final exchange decides who holds this ground.'}</p></div><div className="battle-status"><div><span>Momentum</span><strong>{battle.momentum > 0 ? '+' : ''}{battle.momentum}</strong></div><div><span>Morale</span><strong>{battle.morale}%</strong><Bar value={battle.morale} label="Crew morale" /></div><div><span>Exposure</span><strong>{battle.exposure}%</strong><Bar value={battle.exposure} tone="heat" label="Battle exposure" /></div></div><p className="encounter-target">To win: 30+ momentum · morale above 15 · exposure below 85.</p><div className="strategy-choice-list battle-choices">{candidates.map(choiceId => { const info = battleChoiceInfo(state, choiceId); return <button key={choiceId} className="strategy-choice battle-choice" disabled={info.requirements.length > 0} title={info.requirements.join(' ')} onClick={() => act({ type: 'BATTLE_CHOICE', choiceId })}><div><strong>{info.label}<span>{info.chance}%</span></strong><p>{info.description}</p><div className="choice-resource-line"><span><Lightning size={14} />{info.energy}</span><span>Momentum +{info.momentum}</span><span>Morale {info.morale >= 0 ? '+' : ''}{info.morale}</span><span>Exposure {info.exposure >= 0 ? '+' : ''}{info.exposure}</span><span>Injury {info.injuryChance}%</span></div>{info.requirements[0] && <small>{info.requirements[0]}</small>}</div><ArrowRight size={18} /></button>; })}</div><Button className="full-width encounter-retreat" variant="ghost" disabled={retreat.requirements.length > 0} onClick={() => act({ type: 'BATTLE_CHOICE', choiceId: 'retreat' })}>Withdraw crew<ArrowRight size={16} /></Button><details className="encounter-consequences"><summary>Setbacks & withdrawal</summary><p>A setback gives −8 momentum, an extra −12 morale and +8 exposure. Injury can occur on either outcome.</p><p>Withdraw: −8 Reputation, −15 intel, −5 crew loyalty, +25 fatigue. Preparation costs stay spent.</p></details></Modal>;
}

export function OperationPlanning({ state, act, id, onClose }: ScreenProps & { id: string; onClose: () => void }) {
  const [selected, setSelected] = useState<string[]>([]);
  const operation = operations.find(o => o.id === id);
  if (!operation) return null;
  const entry = operationEntryInfo(state, operation, selected);
  const reasons = entry.requirements;
  return <Modal title="Plan major operation" onClose={onClose} className="strategy-modal"><div className="dialog-art compact-strategy-art" style={{ backgroundImage: `url(${operation.image})` }}><Tag tone="glass">{operation.stages.length} STAGES · REPEATABLE</Tag></div><div className="strategy-dialog-heading"><h2>{operation.name}</h2><p>{operation.description}</p></div><div className="strategy-preview"><div><span>Potential take</span><strong>{money(operation.reward[0], true)}–{money(operation.reward[1], true)}</strong></div><div><span>Preparation</span><strong>{money(entry.cost, true)}</strong></div><div><span>Entry energy</span><strong>{entry.energy}</strong></div></div><CrewSelection state={state} selected={selected} onChange={setSelected} maximum={operation.requiredCrew} />{operation.requiredItems.length > 0 && <div className="operation-kit">{operation.requiredItems.map(itemId => <Tag tone={state.inventory.includes(itemId) ? 'gold' : ''} key={itemId}>{state.inventory.includes(itemId) ? '✓ ' : ''}{items.find(i => i.id === itemId)?.name ?? itemId}</Tag>)}</div>}<Gate reasons={reasons} /><Button className="full-width" disabled={reasons.length > 0} onClick={() => { act({ type: 'START_OPERATION', id, crewIds: selected }); onClose(); }}>Commit operation<ArrowRight size={18} /></Button><p className="dialog-footnote">Stage choices have their own costs. Suspicion compounds; withdrawal remains possible.</p></Modal>;
}

export function OperationEncounter({ state, act }: ScreenProps) {
  const current = getStrategy(state).operation;
  if (!current) return null;
  const operation = operations.find(o => o.id === current.operationId)!;
  const stage = operation.stages[current.stage];
  if (!stage) return null;
  return <Modal title="Major operation stage" dismissible={false} className="strategy-modal encounter-modal"><div className="dialog-art compact-strategy-art" style={{ backgroundImage: `url(${operation.image})` }}><Tag tone="glass">{operation.name.toUpperCase()} · {current.stage + 1}/{operation.stages.length}</Tag></div><div className="strategy-dialog-heading"><span className="eyebrow">{stage.skill.replace(/([A-Z])/g, ' $1')}</span><h2>{stage.name}</h2><p>{stage.description}</p></div><div className="operation-track"><div><span>Progress <strong>{current.progress}%</strong></span><Bar value={current.progress} label="Operation progress" /></div><div><span>Suspicion <strong>{current.suspicion}%</strong></span><Bar value={current.suspicion} tone="heat" label="Operation suspicion" /></div></div><p className="encounter-target">Finish with 85+ progress and suspicion below 80.</p><div className="strategy-choice-list operation-stage-choices">{stage.choices.map(choice => { const info = operationChoiceInfo(state, choice.id); return <button className="strategy-choice" key={choice.id} disabled={info.requirements.length > 0} title={info.requirements.join(' ')} onClick={() => act({ type: 'OPERATION_CHOICE', choiceId: choice.id })}><div><strong>{choice.label}<span>{info.chance}%</span></strong><p>{choice.description}</p><div className="choice-resource-line"><span>{money(info.cost)}</span><span><Lightning size={14} />{info.energy}</span><span>Progress +{info.progress}</span><span>Suspicion {info.suspicion >= 0 ? '+' : ''}{info.suspicion}</span></div>{info.requirements[0] && <small>{info.requirements[0]}</small>}</div><ArrowRight size={18} /></button>; })}</div><Button variant="ghost" className="full-width encounter-retreat" onClick={() => act({ type: 'ABORT_OPERATION' })}>Withdraw from operation<ArrowRight size={16} /></Button><details className="encounter-consequences"><summary>Setbacks & withdrawal</summary><p>A setback gives +10 progress and an extra +18 suspicion. Suspicion at 90 ends the run.</p><p>Withdraw: −10 Reputation, −5 crew loyalty, +25 fatigue. All committed costs stay spent.</p></details></Modal>;
}
