import { useRef, useState } from 'react';
import { ArrowRight, ArrowSquareOut, Crown, DownloadSimple, GearSix, Info, ShareNetwork, ShieldCheck, Star, Trash, UploadSimple } from '@phosphor-icons/react';
import type { GameState, Settings } from '../game/types';
import { activities, districts, events } from '../data';
import { appInfo } from '../services/platform';
import { Button, Modal, Toggle } from './components';

export function SettingsDialog({state,settings,onChange,onClose,onExport,onImport,onReset,onShare,onRate,onAbout,onStore,premium=false,onPrivacy}:{state:GameState|null;settings:Settings;onChange:(s:Settings)=>void;onClose:()=>void;onExport:()=>void;onImport:(file:File)=>void;onReset:()=>void;onShare:()=>void;onRate:()=>void;onAbout:()=>void;onStore:()=>void;premium?:boolean;onPrivacy?:()=>void}){
  const file=useRef<HTMLInputElement>(null);const [reset,setReset]=useState(false);
  return <Modal title="Settings" onClose={onClose} className="settings-modal"><div className="system-dialog-title"><GearSix size={28}/><h2>Make yourself comfortable.</h2></div>{reset?<><div className="reset-notice"><h3>Start with a clean slate?</h3><p>This removes the local story and backup. Export your save first if you want to keep it.</p></div><div className="confirmation-buttons"><Button variant="secondary" onClick={()=>setReset(false)}>Keep my story</Button><Button variant="danger" onClick={onReset}>Delete local save</Button></div></>:<><div className="setting-group"><Toggle label="Sound effects" description="Soft mechanical clicks and tactile cues." value={settings.sound} onChange={()=>onChange({...settings,sound:!settings.sound})}/><Toggle label="City ambience" description="Rain, wind and distant streets. No music." value={settings.music} onChange={()=>onChange({...settings,music:!settings.music})}/><Toggle label="Haptic feedback" value={settings.haptics} onChange={()=>onChange({...settings,haptics:!settings.haptics})}/><Toggle label="Reduce motion" value={settings.reducedMotion} onChange={()=>onChange({...settings,reducedMotion:!settings.reducedMotion})}/><div className="setting-row"><strong>Language</strong><span className="setting-value">English</span></div></div><div className="save-setting-block"><div><ShieldCheck size={19}/><strong>Your story stays with you.</strong></div><p>{state?`Day ${state.day} · ${state.player.name} · saved on this device`:'No local story yet.'}</p><div className="save-buttons"><Button variant="secondary" disabled={!state} onClick={onExport}><DownloadSimple size={17}/>Export save</Button><Button variant="secondary" onClick={()=>file.current?.click()}><UploadSimple size={17}/>Import save</Button></div><input ref={file} type="file" accept=".json,application/json" className="sr-only" aria-label="Import save file" onChange={e=>{const selected=e.target.files?.[0];if(selected)onImport(selected);e.target.value='';}}/></div><div className="settings-links"><button aria-label="Remove ads" onClick={onStore}><Crown size={19}/>{premium?"Remove Ads active":"Remove ads"}<ArrowRight size={16}/></button>{onPrivacy&&<button onClick={onPrivacy}><ShieldCheck size={19}/>Privacy choices<ArrowRight size={16}/></button>}<button onClick={onShare}><ShareNetwork size={19}/>Share BLACKLINE<ArrowRight size={16}/></button><button onClick={onRate}><Star size={19}/>Rate the game<ArrowSquareOut size={16}/></button><button onClick={onAbout}><Info size={19}/>About BLACKLINE<ArrowRight size={16}/></button>{state&&<button className="reset-link" onClick={()=>setReset(true)}><Trash size={19}/>Delete local save<ArrowRight size={16}/></button>}</div></>}</Modal>;
}
export function AboutDialog({onClose}:{onClose:()=>void}){
  return <Modal title="About BLACKLINE" onClose={onClose} className="about-modal"><img src="/assets/icon-192.png" alt="BLACKLINE app icon" className="about-icon"/><span className="eyebrow">RISE FROM THE SHADOWS</span><h2>BLACKLINE<i>.</i></h2><p className="about-lead">An original, offline crime life simulator.<br />One city. Your choices. Your legacy.</p><div className="about-details"><div><span>Version</span><strong>{appInfo.version}</strong></div><div><span>Content</span><strong>{districts.length} districts · {activities.length} operations · {events.length} events</strong></div><div><span>Sound</span><strong>Natural ambience & mechanical SFX</strong></div><div><span>Characters</span><strong>Fully covered faces & opaque masks</strong></div></div><div className="privacy-note"><ShieldCheck size={23}/><div><strong>Your story is private.</strong><p>Progress, art and sound stay on this device for offline play. Optional ads and purchases connect to Google services. You can manage ad privacy choices in Settings.</p></div></div><p className="dialog-footnote">A fictional city and fictional characters. All artwork created for BLACKLINE. Google Play listing will become available after release.</p></Modal>;
}
